### ISSUE TITLE
Request Approval Email Sending 3 Times

### ISSUE THREAD

**Issue by JasonLee4** [RiceAstroparticleLab/xenon-users-web#64] opened 2023-01-24 20:30 UTC
Approval email is being sent three times, to ADMIN, CB, and CHRIS.

**Comment by reallsx** [comment] 2023-01-25 21:38
The cause of this issue is Chris email being in all of the mailing lists.

This is fixed by changing the recipient of the automatic approval email.

**Closed by reallsx** 2023-01-25 21:38 UTC
